_wandb:
    value:
        cli_version: 0.23.1
        e:
            ason5jc9nc5torlu4ydvt9j1br6tdms3:
                apple:
                    ecpuCores: 2
                    gpuCores: 16
                    memoryGb: 16
                    name: Apple M1 Pro
                    pcpuCores: 8
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "5368709120"
                codePath: training/train_ppo.py
                codePathLocal: training/train_ppo.py
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "494384795648"
                        used: "423763927040"
                email: aidanjperuch@gmail.com
                executable: /usr/local/Caskroom/miniforge/base/bin/python
                git:
                    commit: 1093b8d01f62d953eb0826c5bd8b0f2aff586199
                    remote: https://github.com/mantissa-aidan/five_hundred.git
                host: MacBookPro.lan
                memory:
                    total: "17179869184"
                os: macOS-15.6.1-arm64-arm-64bit
                program: /Users/aidanperuch/Code/five_hundred/training/train_ppo.py
                python: CPython 3.10.18
                root: /Users/aidanperuch/Code/five_hundred
                startedAt: "2026-01-03T12:21:02.318735Z"
                writerId: ason5jc9nc5torlu4ydvt9j1br6tdms3
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 105
            "2":
                - 1
                - 105
            "3":
                - 2
                - 13
                - 16
            "4": 3.10.18
            "5": 0.23.1
            "12": 0.23.1
            "13": darwin-arm64
algo:
    value: PPO
gamma:
    value: 0.99
lr:
    value: 0.00025
num_envs:
    value: 16
steps_per_rollout:
    value: 32
total_timesteps:
    value: 5000000
