_wandb:
    value:
        cli_version: 0.23.1
        e:
            1j3vvrnrikxj4g6ajnqb16x5xmsxdy6j:
                apple:
                    ecpuCores: 2
                    gpuCores: 16
                    memoryGb: 16
                    name: Apple M1 Pro
                    pcpuCores: 8
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "4294967296"
                codePath: training/train_agent_wandb.py
                codePathLocal: training/train_agent_wandb.py
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "494384795648"
                        used: "420885975040"
                email: aidanjperuch@gmail.com
                executable: /usr/local/Caskroom/miniforge/base/bin/python
                git:
                    commit: fcb58c7eae47042a2a4674067bd02150ea11eada
                    remote: https://github.com/mantissa-aidan/five_hundred.git
                host: MacBookPro.lan
                memory:
                    total: "17179869184"
                os: macOS-15.6.1-arm64-arm-64bit
                program: /Users/aidanperuch/Code/five_hundred/training/train_agent_wandb.py
                python: CPython 3.10.18
                root: /Users/aidanperuch/Code/five_hundred
                startedAt: "2026-01-03T06:49:20.658275Z"
                writerId: 1j3vvrnrikxj4g6ajnqb16x5xmsxdy6j
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 105
            "2":
                - 1
                - 105
            "3":
                - 13
                - 16
            "4": 3.10.18
            "5": 0.23.1
            "12": 0.23.1
            "13": darwin-arm64
buffer_size:
    value: 50000
gamma:
    value: 0.99
hybrid_learning:
    value: mc_bidding_td_playing
lr:
    value: 0.0001
pretrained:
    value: rules_bot
reward_shaping:
    value: contract_bonus_0.5
state_dim:
    value: 466
update_target_every:
    value: 1000
